---
checks:
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 100
  return-statements:
    config:
      threshold: 20
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - typescript
  eslint:
    enabled: true
    channel: eslint-6
  fixme:
    enabled: true
ratings:
  paths:
    - "*.ts"
    - "test/*.ts"
    - "test/*.js"
