env:
  global:
    - CODECLIMATE_REPO_TOKEN=b96c8e14d13e6e0eac109776042700ebba5cddd019d9031fc476d8110842920f

sudo: false

language: node_js

node_js:
  - "12"
  - "10"

after_script:
  - if [[ `node --version` =~ ^v12 ]] ; then npm run coverage ; npm install codeclimate-test-reporter ; codeclimate-test-reporter < coverage/lcov.info ; fi
